Feature/docu and iet patterns
PatternAtlas/pattern-atlas-content pull request #11
Opened 2021-10-21 11:40 UTC by manuwei

* add iet patterns
* fix some latex statements that our new markdown-it-katexx lib can not handle 

Before merging this PR, the IET Paper should appear and a proper citation to the paper should be added. 
To do this, execute the patternatlas via docker with the PATTERN_ATLAS_CONTENT_REPOSITORY_BRANCH set to this branch and add the paper reference:

step 1: open the pattern settings:
![image](https://user-images.githubusercontent.com/44226745/138268688-9fb17b35-8565-4582-84f0-0df016fc593f.png)

step 2: edit the paper ref
![image](https://user-images.githubusercontent.com/44226745/138269453-6f980844-c899-4d05-b70d-74737744d19f.png)

step 3: perform a database backup with pgadmin (see readme https://github.com/PatternAtlas/pattern-atlas-content) and update db-backup-files/2-patternatlas-data-inserts.sql accordingly

step 4: test and merge the PR

2021-12-17 15:52 UTC, salmma requested changes
See my comments below.

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('e595558d-bfea-4b82-9f47-a38a2097b245', 'Angle Encoding', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatterns/angleEncoding', '{"Alias":
a [ is missing in solution at "taken from ..." such that the link is presented

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('e595558d-bfea-4b82-9f47-a38a2097b245', 'Angle Encoding', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatterns/angleEncoding', '{"Alias":
in addition, in section result, the cite is shown in latex format: "\cite{...}"

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('3f3fabf0-7fa7-4b43-a74a-46a7ac2c55ee', 'Function Table', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatterns/functionTable', '{"Alias":
in section Result, first '' is used instead of "

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('3f3fabf0-7fa7-4b43-a74a-46a7ac2c55ee', 'Function Table', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatterns/functionTable', '{"Alias":
further, in Relations to other Patterns the isRelatedTo is presenting strange rendering--> "Function Table: Applying U_{f}U f ​ Applying U_{f}U f ​ Applying the unitary ..."
same case also in pattern Creating Entanglement

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('d9c57511-1101-4707-99bf-36f43a12cb13', 'Quantum Random Access Memory (QRAM) Encoding', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatte
same as for Angle Encoding: under solution the last link is not presented correctly as a [ is missing

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('d9c57511-1101-4707-99bf-36f43a12cb13', 'Quantum Random Access Memory (QRAM) Encoding', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatte
in the paper it is stated that QPE uses Matrix Encoding and on the other hand that Matrix Encoding can be used to define a unitary operation as input for QPE. 

Here, currently, Matrix Encoding canBeUsedWith QPE is defined in the content. @lharzenetter what do you think?

2021-12-17 15:52 UTC, salmma commented on db-backup-files/2-patternatlas-data-inserts.sql
> +INSERT INTO public.pattern VALUES ('d9c57511-1101-4707-99bf-36f43a12cb13', 'Quantum Random Access Memory (QRAM) Encoding', 'https://patternpedia.org/patternLanguages/reformulatedQuantumComputingPatte
in solution: the SummerSOC paper is still "to appear" and has to be updated

2021-12-20 13:38 UTC, lharzenetter approved these changes
All comments seem to be resolved!

2021-12-20 13:38 UTC, merged